more reverting; then I can merge back up

diff --git a/opennms-daemon/src/main/filtered/bin/opennms b/opennms-daemon/src/main/filtered/bin/opennms
--- a/opennms-daemon/src/main/filtered/bin/opennms
+++ b/opennms-daemon/src/main/filtered/bin/opennms
@@ -157,14 +157,14 @@ checkXmlFiles(){
 				echo "ERROR: XML validation failed: $FILE"
 				echo "	   run '$XMLLINT $FILE' for details"
 			fi
-		done >"$TEMPFILE"
-		cat "$TEMPFILE"
-		FAILCOUNT=`cat "$TEMPFILE" | grep -c 'XML validation failed'`
-		rm "$TEMPFILE"
-		if [ $FAILCOUNT -gt 0 ]; then
-			echo "Validation failed on $FAILCOUNT XML files.  Exiting."
-			exit 1
-		fi
+			done >"$TEMPFILE"
+			cat "$TEMPFILE"
+			FAILCOUNT=`cat "$TEMPFILE" | grep -c 'XML validation failed'`
+			rm "$TEMPFILE"
+			if [ $FAILCOUNT -gt 0 ]; then
+				echo "Validation failed on $FAILCOUNT XML files.  Exiting."
+				exit 1
+			fi
 	fi
 		 
 	return 0
@@ -547,20 +547,10 @@ if [ x"$VERBOSE_GC" != x"" ]; then
 fi
 
 if [ ! -f $OPENNMS_HOME/etc/configured ]; then
-	cat <<END >&2
-$0: OpenNMS not configured.
-$OPENNMS_HOME/etc/configured does not exist.
-
-You need to run the installer to set up the database.  In most
-cases, it is enough to run:
-
-  $OPENNMS_HOME/bin/install -dis
-
-For details, see the install guide at:
-
-http://www.opennms.org/index.php/QuickStart#Initialize_OpenNMS_and_the_Database
-
-END
+	echo "$0: OpenNMS not configured." >&2
+	echo "$OPENNMS_HOME/etc/configured does not exist." >&2
+	echo "You need to run the installer to setup the database -- see the" >&2
+	echo "install guide for details." >&2
 	exit 6	# From LSB: 6 - program is not configured
 fi
 
